version: '3'

services:
  geth:
    image: ulamlabs/geth-poa-testnet:latest
    environment:
      - ETH_PASSWORD=signer
      - ETH_PRIVATE_KEY=68c9bbfbea1935530544c8d533b39c48241164a37db7ea5c490a259a9a669d95
      - ETH_ADDRESS=33f471aC652142ab6b7A7E13177516d477f269DD
    ports:
      - 8178:8178
      - 8546:8546
    volumes:
      - ./louiz.json:/app/genesis.json

  blockscout:
    image: ulamlabs/blockscout:latest
    links:
      - geth
      - postgres
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?ssl=false
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8178
      - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546
      - MIX_ENV=prod
      - BLOCKSCOUT_HOST=localhost
      - COIN=LOUIZ
      - NETWORK=LOUIZ
      - SUBNETWORK=Louiz Testnet
      - LOGO=/images/louizexp.png
      - LOGO_FOOTER=/images/louizexp.png
      - DISABLE_EXCHANGE_RATES=true
      - APPS_MENU=false
      - SUPPORTED_CHAINS=[]
      - SHOW_ADDRESS_MARKETCAP_PERCENTAGE=false
      - SHOW_TESTNET_LABEL=true
    volumes:
      - ./louizexp.png:/opt/app/apps/block_scout_web/priv/static/images/louizexp.png

  postgres:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
